title: 我的网络日志
url: "/"
baseurl: ""

theme: minima
markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://cuishifeng.life"
footer_text: "崔世峰的博客 - Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jekyll-feed

nav:
 - name: "First"
   link: "/"
 - name: "About"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
