title: Simple
url: ""
baseurl: ""

theme: minima
markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://shifengcui.github.io"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jekyll-feed

nav:
 - name: "About"
   link: ""
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
